### ISSUE TITLE
not uploading images, by local file and google drive

### ISSUE THREAD

**Issue by bezdna** [hotosm/OpenAerialMap#145] opened 2021-03-31 16:32 UTC
![image](https://user-images.githubusercontent.com/518939/113178872-af8d1180-9257-11eb-93a5-c81f09a842ca.png)
and 
https://map.openaerialmap.org/#/upload/status/6064982fd8a0ef00061b94e5?_k=u81xii

**Comment by cgiovando** [comment] 2021-04-09 08:41
Hi @bezdna - I tried different uploads, but could not reproduce this error. Can you check the dates forms, and try to select date and time manually from the dropdowns? Sometimes manually entering the time can cause similar form issues.

**Comment by bezdna** [comment] 2021-04-09 09:21
![image](https://user-images.githubusercontent.com/518939/114159044-0a94c780-992e-11eb-95bc-1595e6d0480e.png)
same

**Comment by bezdna** [comment] 2021-04-09 09:23
https://drive.google.com/file/d/17jQ61gsF0NtrB5EYeU6EW8aZ9s5MJbAt/view file that I use for upload, there might be a problem in the file

**Comment by cgiovando** [comment] 2021-04-13 14:29
Hi @bezdna - yes, it looks like your file does not have proper GeoTIFF metadata, and missing georeferencing information:

> Warning 1: TIFFReadDirectoryCheckOrder:Invalid TIFF directory; tags are not sorted in ascending order
Driver: GTiff/GeoTIFF
Files: /X-44-52-В-а-2.tif
Size is 9045, 9460
Coordinate System is `'
Metadata:
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_XRESOLUTION=508
  TIFFTAG_YRESOLUTION=508
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 9460.0)
Upper Right ( 9045.0,    0.0)
Lower Right ( 9045.0, 9460.0)
Center      ( 4522.5, 4730.0)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue

Can you try fixing that and try the upload again?

**Comment by cgiovando** [comment] 2021-04-26 09:10
Closing for now, please reopen if the issue persists.

**Closed by cgiovando** 2021-04-26 09:10 UTC
Labels: v1 fix
