### ISSUE TITLE
über WMTS 

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenAerialMap#62] opened 2017-02-15 15:31 UTC
From #59, we punted on addressing a WMTS endpoint that incorporates / points to all known endpoints. 

from @mojodna, 
> I think so, with some extra work. I can't remember if WMTS can delegate to other endpoints or if we'd need to load and duplicate all of the available ones (zoom ranges are particularly repetitive).

Need to do some research on feasibility here.

**Comment by cgiovando** [comment] 2021-04-14 08:09
Duplicate of #108

**Closed by cgiovando** 2021-04-14 08:09 UTC
