### ISSUE TITLE
Problem loading data using by Permalink in Chrome/Firefox browser

### ISSUE THREAD

**Issue by mapconcierge** [hotosm/OpenAerialMap#133] opened 2018-10-03 05:42 UTC
Permalink is not available.

Example: 
https://map.openaerialmap.org/#/139.53718185424805,35.64836915737426,12/square/13300211221312/59e62bb13d6412ef7220aedd?_k=8ffnv4

>>> no response, and white page.

<img width="1440" alt="2018-10-03 14 41 27" src="https://user-images.githubusercontent.com/416977/46392004-905ea900-c71a-11e8-95d3-42051427c2c1.png">

**Comment by smit1678** [comment] 2018-10-05 12:10
@mapconcierge yeah, this happens with either old (pre summer 2017 URLs) or if you get something wrong with the parameters. The current state of URL sharing isn't ideal and leads to it breaking. I would encourage sharing your user page (https://map.openaerialmap.org/#/137.559814453125,35.96022296929667,6/user/5b0257e42b6a08001185f157) or the image directly (https://map.openaerialmap.org/#/135.31425699999997,34.707034075401566,16/square/13300202/5b925da45d406700087d1514). Sharing the selected grid cell seems to create some errors more than the others.

**Comment by cgiovando** [comment] 2021-04-13 14:38
Possible duplicate of https://github.com/hotosm/oam-browser/issues/290

**Closed by cgiovando** 2021-04-13 14:38 UTC
